### ISSUE TITLE
Mismatches between image filenames in CC3M. 

### ISSUE THREAD

**Issue by Dwrety** [CVMI-Lab/CoDet#12]
Hello, we want to reproduce the work of your paper and we are stuck on the files. Basically the file "train_image_info_tags_4706.json" is pointing to the incorrect images of the cc3m dataset. We find that they are not the correct match.

**Comment by machuofan** [comment]
Hello, could you please provide more details on how you download the cc3m dataset and the filename format of your dataset?

**Comment by seermer** [comment]
> Hello, could you please provide more details on how you download the cc3m dataset and the filename format of your dataset?

Hello, thanks for the reply. When downloading cc3m with tools/download_cc.py, the filenames correspond to the row number in raw annotation file GCC-training.tsv (e.g., first row of tsv correspond to 1.jpg).
However, in "train_image_info_tags_4706.json", 1.jpg correspond to caption "a portrait of person a member of the team", while in GCC-training.tsv, first row correspond to caption "a very typical bus station". In "train_image_info_tags_4706.json", 2.jpg correspond to caption "this map really illustrates how dynamic our planet is .", while in GCC-training.tsv, second row correspond to caption "sierra looked stunning in this top and this skirt while performing with person at their former university". Similarly, this mismatch happens for the rest of the annotations in the json file, and the image shape/aspect ratio recorded in the json file also doesn't match the actual images. I have also manually inspected each image, and the captions from "train_image_info_tags_4706.json" do not match the downloaded images.

I have looked at the annotation file downloaded from different sources (including the official website https://ai.google.com/research/ConceptualCaptions/download and some third-party downloads), and this mismatch is true for all versions.

**Comment by Dwrety** [comment]
> > Hello, could you please provide more details on how you download the cc3m dataset and the filename format of your dataset?
> 
> Hello, thanks for the reply. When downloading cc3m with tools/download_cc.py, the filenames correspond to the row number in raw annotation file GCC-training.tsv (e.g., first row of tsv correspond to 1.jpg). However, in "train_image_info_tags_4706.json", 1.jpg correspond to caption "a portrait of person a member of the team", while in GCC-training.tsv, first row correspond to caption "a very typical bus station". In "train_image_info_tags_4706.json", 2.jpg correspond to caption "this map really illustrates how dynamic our planet is .", while in GCC-training.tsv, second row correspond to caption "sierra looked stunning in this top and this skirt while performing with person at their former university". Similarly, this mismatch happens for the rest of the annotations in the json file, and the image shape/aspect ratio recorded in the json file also doesn't match the actual images. I have also manually inspected each image, and the captions from "train_image_info_tags_4706.json" do not match the downloaded images.
> 
> I have looked at the annotation file downloaded from different sources (including the official website https://ai.google.com/research/ConceptualCaptions/download and some third-party downloads), and this mismatch is true for all versions.

Yes, this is the problem. We followed the row number of GCC-training.tsv to name the images. The 1st row image is named 1.jpg, 2nd row named 2.jpg. And the downloading process loops through this file and generates {1, 2, 3, ...}.jpg in a sequence. However, we found that all files are mismatched. Is there a way to fix this? Thank you.

**Comment by machuofan** [comment]
Thanks for pointing out this mistake. I see the problem. Here is a quick fix: You may have a try using the captions in 'train_image_info_tags_4706.json' to locate the the row in GCC-training.tsv.

For example, "a portrait of person a member of the team" points to the 779864th row in GCC-training.tsv. Thus you can replace '1.jpg' in 'train_image_info_tags_4706.json' with '779864.jpg'. Notably, there could be more than one match for a caption, in this case you also need to match the image width and height. Hope this would be helpful.

**Comment by machuofan** [comment]
We have now uploaded the scripts to extract and filter noun phrase from the original captions. You can now generate 'train_image_info_tags_4706.json' with your own 'train_image_info.json'. Please refer to [Data.md](https://github.com/CVMI-Lab/CoDet/blob/main/docs/DATA.md#conceptual-caption) for detailed instructions.

**Comment by Dwrety** [comment]
> We have now uploaded the scripts to extract and filter noun phrase from the original captions. You can now generate 'train_image_info_tags_4706.json' with your own 'train_image_info.json'. Please refer to [Data.md](https://github.com/CVMI-Lab/CoDet/blob/main/docs/DATA.md#conceptual-caption) for detailed instructions.

Thank you, I will take a look
