### ISSUE TITLE
LVIS uses 866 base classes during training, but does it use the complete 1203 classes for verification?

### ISSUE THREAD

**Issue by zhongzee** [CVMI-Lab/CoDet#16]
python tools/remove_lvis_rare.py --ann datasets/lvis/lvis_v1_train.json ;There is no need to remove rare classes in the validation set, right?

**Comment by machuofan** [comment]
Yes, `remove_lvis_rare.py` is only applied to `lvis_v1_train.json`. We use the full validation set for evaluation.

**Comment by zhongzee** [comment]
![image](https://github.com/CVMI-Lab/CoDet/assets/45118059/de10a19b-748e-44b5-a263-534187e5a9b7)
Thank you for your reply. Is this a common practice in OVD? So when you finally calculate the indicators in Table 1, how do you distinguish the categories of novel, common, and frequency? Do you use the labels that come with the data set?

**Comment by machuofan** [comment]
Yes, this is a standard practice. Class frequency, e.g., rare, common, and frequent, is recorded in LVIS annotations. Please refer to our code for more details.
