### ISSUE TITLE
The working mechanism of the classifier

### ISSUE THREAD

**Issue by zhangyupeng123** [CVMI-Lab/CoDet#17]
Dear author, thank you very much for your excellent work. I have a question that I would like to ask you. Is the classifier designed to calculate the cosine similarity between images and text in the same way as CLIP, or is it designed differently? I don't seem to have found detailed information on this part.

**Comment by machuofan** [comment]
Hi there, thank you for your interest in our work. Yes, the classifier works in the same way as CLIP, i.e, the classifier weights are essentially composed of text embeddings.

**Comment by zhangyupeng123** [comment]
When training, is the input on the text side the image's title, or is it just a template like "a photo of <class name>" or "a <class name>"?

**Comment by zhangyupeng123** [comment]
@machuofan  When training, is the input on the text side the image's title, or is it just a template like "a photo of <class name>" or "a <class name>"?

**Comment by machuofan** [comment]
It's 'a xxx'.
