### ISSUE TITLE
Where should I find the core part code

### ISSUE THREAD

**Issue by gintmr** [CVMI-Lab/CoDet#19]
I have been studying this code for a long time, but I have never found the core code of the paper.
could you tell me which part of the code is finding the **Co-Occurrence Region** ？ thx

**Comment by machuofan** [comment]
Hi there, you can find the code snippet [here](https://github.com/CVMI-Lab/CoDet/blob/803bd3e8684527701b24163a2db560d10c5dd99d/codet/modeling/roi_heads/codet_fast_rcnn.py#L611).
