### ISSUE TITLE
About training cost.

### ISSUE THREAD

**Issue by guangpintao** [CVMI-Lab/CoDet#2]
Thank you for the open source. How long will it take to train with 8 GPUs on the LVIS+CC3M training set？

**Comment by machuofan** [comment]
It takes roughly 20 hours on 8 A100s.

**Comment by guangpintao** [comment]
Thank you for your answer. By the way, the download of the CC3M dataset is slow and it seems that many image links are invalid. Is it possible to download it entirety?

**Comment by machuofan** [comment]
Yes, expired URL is a common issue in downloading CC3M. But there is not much we can do about it as we do not have licenses on these images. 

For the downloading speed, you may try multi-processing in your script. Hope this [script](https://huggingface.co/spaces/flax-community/dalle-mini/blob/75b01a0a3a29bb2eb6962f5f2fdf160e5c784647/data/CC3M_downloader.py) will help you.

**Comment by guangpintao** [comment]
Your help was very much appreciated.

**Comment by kinredon** [comment]
@machuofan How many images of CC3M have you downloaded?
