### ISSUE TITLE
 AttributeError: 'Linear' object has no attribute 'linear'

### ISSUE THREAD

**Issue by junnnxie** [CVMI-Lab/CoDet#4]
I have a problem while training, at CoDet-main/codet/modeling/roi_heads/codet_roi_heads.py, line 255, in _run_stage
boxes_features_copy = self.box_predictor[stage].cls_score.linear(box_features)
raise AttributeError('''{}' object has no attribute '{}'''.format(
AttributeError: 'Linear' object has no attribute 'linear')

I'm trying to run the CoDet training code, but I encountered this problem. I hope someone can help me.

**Comment by machuofan** [comment]
Are you running the training config [Base_OVLVIS_R5021k_4x.yaml](https://github.com/CVMI-Lab/CoDet/blob/main/configs/Base_OVLVIS_R5021k_4x.yaml)? This bug stems from not using ZeroShotClassifier as the classifier head. A quick fix is to switch [line 255](https://github.com/CVMI-Lab/CoDet/blob/f289e5db485f406d991b2f2fdb76869e7ee93654/codet/modeling/roi_heads/codet_roi_heads.py#L255) and [line 256](https://github.com/CVMI-Lab/CoDet/blob/f289e5db485f406d991b2f2fdb76869e7ee93654/codet/modeling/roi_heads/codet_roi_heads.py#L256C9-L256C37).

**Comment by junnnxie** [comment]
Yes, the data I have prepared now can meet the requirements of config Base_OVLVIS_R5021k_4x.yaml, and I want to run it.
How does the "switch" you mentioned operate? Should the order of these two lines of code be changed?

**Comment by machuofan** [comment]
Yes, I have now fixed the code in codet_roi_heads.py. You may take a look at it.

**Comment by sssssshf** [comment]
> Yes, I have now fixed the code in codet_roi_heads.py. You may take a look at it.

Can you share all of your installation packages ablout pip list？

**Comment by sssssshf** [comment]
> Yes, I have now fixed the code in codet_roi_heads.py. You may take a look at it.
torch==1.12.1 torchvision==0.13.1
    @torch.library.custom_op("apex::fused_rms_norm_affine_fwd", mutates_args=())
AttributeError: module 'torch.library' has no attribute 'custom_op'
