### ISSUE TITLE
lvis_v1_train_norare_cat_info.json

### ISSUE THREAD

**Issue by junnnxie** [CVMI-Lab/CoDet#6]
Hello, when I tried to use config CoDet_OVLVIS_SwinB_4x_ft4x.yaml to train, a prompt appeared that the file 
 `lvis_v1_train_norare_cat_info.json`  was missing. Can you tell me how to obtain this file? Thank you very much

**Comment by machuofan** [comment]
Hi, you need to run
```
python tools/remove_lvis_rare.py --ann datasets/lvis/lvis_v1_train.json
```
Please refer to [DATA.md](https://github.com/CVMI-Lab/CoDet/blob/main/docs/DATA.md) for details.

**Comment by junnnxie** [comment]
Thank you for your reply. I generated `lvis_v1_train_norare.json` according to DATA.md, but the configuration file requires `lvis_v1_train_norare_cat_info.json`. Are these two the same file, or does the later file need to be generated separately?

**Comment by machuofan** [comment]
Sorry. My mistake. You can get `lvis_v1_train_norare_cat_info.json` by running
```
python tools/get_lvis_cat_info.py --ann datasets/lvis/lvis_v1_train_norare.json --add_freq
```

**Comment by junnnxie** [comment]
Thx a lot!

**Comment by sssssshf** [comment]
> Sorry. My mistake. You can get `lvis_v1_train_norare_cat_info.json` by running
> 
> ```
> python tools/get_lvis_cat_info.py --ann datasets/lvis/lvis_v1_train_norare.json --add_freq
> ```

能说明一下配置文件如和修改数据集么,全量数据集coco+obj+lvis该如何设置参数? DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)这俩我咋没找到这个文件夹的?
